name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  module_name:  # id of input
    description: 'Who to greet'
    required: true
outputs:
  var: # id of output
    description: 'The version to fetch for the module'
runs:
  using: 'node16'
  main: 'index.js'