on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        uses: demotcsorg/version_fetch@v1.1
        with:
          who-to-greet: 'Mona the Octocat'

